# This workflow will build a Java project with Maven

# For more information see:
# https://github.com/chetabahana/skema#running-manually
# https://chetabahana.github.io/styles/skema/doc/index.html

name: Java CI with Maven

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!backup'
      - '!Chetabahana'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Xsltdoc
      run: |
        printenv
        java -jar lib/saxon9he.jar xsltdoc-config.xml xsl/xsltdoc.xsl
#        java -jar lib/saxon-he-10.3.jar xsltdoc-config.xml xsl/xsltdoc.xsl 
        cd $GITHUB_WORKSPACE/docs && ls -alR
        sudo apt-get update > /dev/null 2>&1
        sudo apt-get --assume-yes install expect > /dev/null 2>&1
        eval `ssh-agent`
        cd $HOME && ls -al
#         && expect $HOME/.ssh/agent
#        git clone git@github.com:Chetabahana/chetabahana.github.io.git
#        cd $GITHUB_WORKSPACE/chetabahana.github.io && ls -al
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
