# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ Chetabahana ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Run Package
      run: |
        printenv
        cd $GITHUB_WORKSPACE && ls -al
